require 'rbconfig'

namespace :zklock do
  task :clean do
    if File.exists?('Makefile')
      sh 'make clean'
      rm 'Makefile' # yep, regenerate this
    else
      $stderr.puts "nothing to clean, no Makefile"
    end
  end

  task :clobber => :clean do
    rm_rf %w[Makefile c lib bin include ._c]
  end
end

task :clean    => 'zklock:clean'
task :clobber  => 'zklock:clobber'
task :default  => :build

file 'Makefile' do
  sh "ruby extconf.rb"
end

task :build => [ 'Makefile' ] do
  sh 'make'
end
